version: '3.8'

name: pricing-scraper

services:
  pricing-scraper:
    build:
      context: ./scraper
      dockerfile: Dockerfile
    init: true
    environment:
      SCRAPER_TYPE: pricing
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      DELAY_MILLIS: 2000
      DB_HOST: turtrack-manager-db
      DB_PORT: 5432
      DB_NAME: turtrack_manager_db
      DB_USER: turtrack_user
      DB_PASSWORD: turtrack_password
      PROXY_AUTH: intellicode:T3yGrF8Nr63U7q8m
      PROXY_SERVER: https://proxy.packetstream.io:31111
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        order: stop-first
    networks:
      - turo_scraper_network
      - turtrack_common_network
      - kafka_network
      - turtrack-manager-network
    ports:
      - "5011"
      - "9229:9229"
    healthcheck:
      test: ["CMD", "node", "/usr/src/app/healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  turo_scraper_network:
    name: turo_scraper_network
  turtrack_common_network:
    external: true
  kafka_network:
    external: true
  turtrack-manager-network:
    external: true