version: '3.8'


name: pricing-scraper

services:
  pricing-scraper:
    build:
      context: ./scraper
      dockerfile: Dockerfile
    volumes:
      - turo_scraper_data:/usr/src/app/database
    environment:
      SCRAPER_TYPE: pricing
      KAFKA_BROKERS: kafka:29092  # Use the internal Kafka port
    deploy:
      replicas: 10
    networks:
      - turo_scraper_network
      - turtrack_common_network
      - kafka_network
    ports:
      - "5011-5021:5011"
      - "9229-9239:9229"  # debugging port
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:5003/health"]
#      interval: 30s
#      timeout: 10s
#      retries: 3
#      start_period: 10s
#    depends_on:
#      kafka:
#        condition: service_healthy

volumes:
  turo_scraper_data:
    external: true

networks:
  turo_scraper_network:
  turtrack_common_network:
    external: true
  kafka_network:
    external: true