version: '3.8'

name: pricing-scraper

services:
  pricing-scraper:
    build:
      context: ./scraper
      dockerfile: Dockerfile
    volumes:
      - turo_scraper_data:/usr/src/app/database
    environment:
      SCRAPER_TYPE: pricing
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092  # Use the internal Kafka port
      DELAY_MILLIS: 2000
    deploy:
      replicas: 8
      update_config:
        parallelism: 2
        order: stop-first
    networks:
      - turo_scraper_network
      - turtrack_common_network
      - kafka_network
    ports:
      - "5011"
      - "9229"  # debugging port
    healthcheck:
      test: ["CMD", "node", "/usr/src/app/healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  turo_scraper_data:
    external: true

networks:
  turo_scraper_network:
  turtrack_common_network:
    external: true
  kafka_network:
    external: true