version: "3.9"

services:
  calibrator:
    build: ./calibrator
    environment:
      PORT: 5003
    expose:
      - "5003"

  scraper:
    build: ./scraper
    volumes:
      - ./scraper/src:/usr/src/app/src
      - shared:/usr/src/app/database
    ports:
      - "5001-5011:5001"
      - "9229-9239:9229"  # debugging port
    environment:
      PORT: 5001
    depends_on:
      - calibrator
    deploy:
      replicas: 10
      update_config:
        parallelism: 2
        order: stop-first
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s

  plotter:
    build: ./plotter
    volumes:
      - ./plotter/src:/usr/src/app/src
      - shared:/usr/src/app/public/database/
    environment:
      PORT: 5002
    ports:
      - "5002:5002"

volumes:
  shared: