version: '3.8'

name: data-processing

services:

  # Data Processing Services
  data-processor-service:
    build:
      context: ./data-processor-service
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/turo
      SPRING_DATASOURCE_USERNAME: turo_user
      SPRING_DATASOURCE_PASSWORD: turo_password
    networks:
      - turo_scraper_network
      - turtrack_common_network
      - kafka_network

  data-persistor-service:
    build:
      context: ./data-persistor-service
      dockerfile: Dockerfile
    ports:
      - "8088:8088"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/turo
      SPRING_DATASOURCE_USERNAME: turo_user
      SPRING_DATASOURCE_PASSWORD: turo_password
    networks:
      - turo_scraper_network
      - turtrack_common_network
      - kafka_network


volumes:
  turo_scraper_data:
    external: true

networks:
  turo_scraper_network:
  turtrack_common_network:
    external: true
  kafka_network:
    external: true