# No version specified as it's no longer needed in recent Docker Compose versions

services:
  # Turo-scraper services
  calibrator:
    extends:
      file: ./turo-scraper/docker-compose.yml
      service: calibrator

  scraper:
    extends:
      file: ./turo-scraper/docker-compose.yml
      service: scraper
    volumes:
      - shared-data:/usr/src/app/database
    depends_on:
      - kafka
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092

  plotter:
    extends:
      file: ./turo-scraper/docker-compose.yml
      service: plotter
    volumes:
      - shared-data:/usr/src/app/public/database/

  # Kafka and Zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  # Kafka UI
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: default
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: 'kafka:29092,localhost:29092,localhost:9092,kafka:9092'
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
      DYNAMIC_CONFIG_ENABLED: "true"
    depends_on:
      - kafka
      - zookeeper
#    volumes:
#      - ~/kui/config.yml:/etc/kafkaui/dynamic_config.yaml


  # Data Processor Service
  data-processor-service:
    build:
      context: ./turtrack-file-processing/data-processor-service
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    depends_on:
      - kafka
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/turo
      SPRING_DATASOURCE_USERNAME: turo_user
      SPRING_DATASOURCE_PASSWORD: turo_password

  # Data Persistor Service
  data-persistor-service:
    build:
      context: ./turtrack-file-processing/data-persistor-service
      dockerfile: Dockerfile
    ports:
      - "8088:8088"
    depends_on:
      - kafka
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/turo
      SPRING_DATASOURCE_USERNAME: turo_user
      SPRING_DATASOURCE_PASSWORD: turo_password



volumes:
  shared-data:
